package kt.dnd.character;

public enum Perk {
    AGILE,
    ARCANE_MASTERY,
    BRAWLER,
    BLACKSMITH,
    CALL_OF_THE_WOODS,
    CHARISMATIC,
    CHARLATAN,
    DISTRACTED,
    EAGLE_EYE,
    GROUND_FIGHTING,
    HERMIT,
    INNER_FIRE,
    KNIGHT_IN_SHINING_ARMOR,
    LIMP,
    POSSESSED,
    PYROPHOBIA,
    SHY,
    SIXTH_SENSE,
    SWORDSMAN,
    THROWING_PROFICIENCY,
    WANTED;
}
